Repository nhsx/au-data-engineering, pull requests merged in 2021-09, with the labels that each got.

#3 Sql pipeline template
  docs/source/_static/img/pipeline_temps/sql-ingest.png
  docs/source/adfpipelines.rst
  docs/source/index.rst
Labels: enhancement

#4 Sql pipeline template
  config-files/adf-templates/sql-ingestion.json
  docs/source/_static/img/pipeline_temps/sql-ingest.png
  docs/source/adfpipelines.rst
Labels: enhancement

#6 Added first processing pipeline template
  config-files/adf-templates/databricks-processing.json
  docs/source/_static/img/pipeline_temps/databricks/databricks.png
  docs/source/_static/img/pipeline_temps/databricks/databricks1.png
  docs/source/_static/img/pipeline_temps/databricks/databricks2.png
  docs/source/_static/img/pipeline_temps/databricks/databricks3.png
  docs/source/_static/img/pipeline_temps/databricks/databricks4.png
  docs/source/adfpipelines.rst
  docs/source/adfutilities.rst
Labels: documentation, enhancement

#8 excel-sheet-ingestion-added
  config-files/adf-templates/excel-sheet-ingestion.json
  docs/source/_static/img/pipeline_temps/databricks-ingest.png
  docs/source/_static/img/pipeline_temps/excel_sheet_ingestion.png
  docs/source/adfpipelines.rst
Labels: documentation

#9 test of markdown support
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/test.md
Labels: enhancement

#11 Changed overview to markdown
  README.md
  docs/source/index.rst
  docs/source/readme.md
  docs/source/readme.rst
Labels: documentation
